spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/coupon?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: coupon
    password: yeji961126
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true
#  thymeleaf:
#    prefix: classpath:/templates/main/
#    suffix: .html

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace

application:
  title: NHN-Student
  version: 1.0
server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,beans,counter
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
nhn:
  student:
    name: seunggu

com:
  nhn:
    account:
      system:
        version: 1.0.0


info:
  test: taco